### PR TITLE
use default config while booting fitimage

### PR DESCRIPTION
**Pull request by Avinash95**
this connects #31
Signed-off-by: Avinash Tahakik <avinash.tahakik@imgtec.com>

### CODE REVIEW

**Review by Ham22 — DISMISSED** [review]
Acceptance criteria requires us to be able to still override the default from uboot command line. Thats not possible with this change.

**Review by abhijit-mahajani-imgtec — COMMENTED** [review]
Looks good to me. Verified by flashing this bootloader and openwrt can boot fine.

**Comment by nikhil-zinjurde-imgtec** [comment]
Verification failed for the last acceptance criteria in #31 
* successfully boots the default set for buildroot and openwrt images

I flashed a buildroot image "rootfs_79_2017-01-18_121059_root.ubi" from http://imgsysart01.hh.imgtec.org/artifactory/agile-builds-local/variant-001/1487/ using ubiformat command.  On booting with buildroot image, it fails with a stacktrace and goes into a reboot cycle.

**Review by nikhil-zinjurde-imgtec — APPROVED** [review]

**Comment by abhijit-mahajani-imgtec** [comment]
It was merged since the buildroot side needs to be updated to change default config to 'pistachio_marduk_config@1' in the fitImage description file.

**Pull request merged**
